# Rubocop docs: http://rubocop.readthedocs.io/en/latest/

inherit_gem:
  scc-codestyle:
    - default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - kitchen/cookbooks/**/*
    - kitchen/tmp/**/*
    - vendor/**
    - package_obs/**/*
    - package_ibs/**/*

HashSyntax:
  Enabled: false

SpaceInsideBlockBraces:
  EnforcedStyle: space
  SpaceBeforeBlockParameters: false

FileName:
  Exclude:
    - SUSEConnect
    - suse-connect.gemspec
