# Rubocop docs: http://rubocop.readthedocs.io/en/latest/

inherit_gem:
  scc-codestyle:
    - default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - kitchen/cookbooks/**/*
    - kitchen/tmp/**/*
    - vendor/**
    - package/**

ClassLength:
  Max: 128

HashSyntax:
  Enabled: false

MethodLength:
  Max: 15

LineLength:
  Max: 160

SpaceBeforeBlockBraces:
  Enabled: true
  EnforcedStyle: space

SpaceInsideBlockBraces:
  EnforcedStyle: space
  SpaceBeforeBlockParameters: false

EmptyLinesAroundMethodBody:
  Enabled: false

EmptyLinesAroundClassBody:
  Enabled: false

EmptyLinesAroundModuleBody:
  Enabled: false

SignalException:
  Enabled: false

DoubleNegation:
  Enabled: false

PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '{}'

SpaceBeforeFirstArg:
  Enabled: false

FileName:
  Exclude:
    - SUSEConnect
    - suse-connect.gemspec

ClassAndModuleChildren:
  Enabled: false

GlobalVars:
  AllowedVariables: []
