projects:

  connect:
    docker-build-image: cd ..; docker build -t connect.15sp0 -f Dockerfile.15sp0 .
    docker-run-tests: cd ..; docker run --privileged --rm -t connect.15sp0 ./docker/prophet_tests.sh
